name: nsc2026
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - aws-c-auth=0.9.3=h2970c50_0
  - aws-c-cal=0.9.13=h46f3b43_1
  - aws-c-common=0.12.6=hfd05255_0
  - aws-c-compression=0.3.1=hcb3a2da_9
  - aws-c-event-stream=0.5.7=ha388e84_1
  - aws-c-http=0.10.7=hc678f4a_5
  - aws-c-io=0.23.3=h0d5b9f9_5
  - aws-c-mqtt=0.13.3=hfa314fa_11
  - aws-c-s3=0.11.3=ha659bf3_1
  - aws-c-sdkutils=0.2.4=hcb3a2da_4
  - aws-checksums=0.2.7=hcb3a2da_5
  - aws-crt-cpp=0.35.4=hca034e6_0
  - aws-sdk-cpp=1.11.606=hac16450_10
  - backports.zstd=1.3.0=py311h71c1bcc_0
  - bokeh=3.8.2=pyhd8ed1ab_0
  - brotli=1.2.0=h2d644bc_1
  - brotli-bin=1.2.0=hfd05255_1
  - brotli-python=1.2.0=py311hc5da9e4_1
  - bzip2=1.0.8=h0ad9c76_8
  - c-ares=1.34.6=hfd05255_0
  - ca-certificates=2026.1.4=h4c7d964_0
  - cairo=1.18.4=h477c42c_1
  - click=8.3.1=pyha7b4d00_1
  - cloudpickle=3.1.2=pyhcf101f3_1
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py311h275cad7_4
  - cycler=0.12.1=pyhcf101f3_2
  - cytoolz=1.1.0=py311h3485c13_1
  - dask=2026.1.2=pyhcf101f3_0
  - dask-core=2026.1.2=pyhcf101f3_0
  - distributed=2026.1.2=pyhcf101f3_0
  - double-conversion=3.4.0=hac47afa_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py311h3f79411_0
  - freetype=2.14.1=h57928b3_0
  - fsspec=2026.1.0=pyhd8ed1ab_0
  - graphite2=1.3.14=hac47afa_2
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.3.2=h5a1b470_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.2=h637d24d_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.3.0=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhcf101f3_1
  - kiwisolver=1.4.9=py311h275cad7_2
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.18=hf2c6c5f_0
  - lerc=4.0.0=h6470a55_1
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libarrow=23.0.0=h7d27241_1_cuda
  - libarrow-acero=23.0.0=h7d8d6a5_1_cuda
  - libarrow-compute=23.0.0=h2db994a_1_cuda
  - libarrow-dataset=23.0.0=h7d8d6a5_1_cuda
  - libarrow-substrait=23.0.0=hf865cc0_1_cuda
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libclang13=21.1.8=default_ha2db4b5_3
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.18.0=h43ecb02_0
  - libdeflate=1.25=h51727cc_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h3d046cb_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libgcc=15.2.0=h8ee18e1_17
  - libglib=2.86.3=h0c9aed9_0
  - libgomp=15.2.0=h8ee18e1_17
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.2=default_h4379cf1_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - liblzma=5.8.2=hfd05255_0
  - libparquet=23.0.0=h7051d1f_1_cuda
  - libpng=1.6.54=h7351971_0
  - libprotobuf=6.31.1=hdcda5b4_4
  - libre2-11=2025.11.05=h0eb2380_0
  - libsqlite=3.51.2=hf5d6505_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libtiff=4.7.1=h8f73337_1
  - libutf8proc=2.11.3=hb980946_0
  - libvulkan-loader=1.4.341.0=h477610d_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.15.1=h779ef1b_1
  - libxml2-16=2.15.1=h3cfd58e_1
  - libxslt=1.1.43=h0fbe4c1_1
  - libzlib=1.3.1=h2466b09_2
  - llvm-openmp=21.1.8=h4fa8253_0
  - llvmlite=0.46.0=py311h4f568be_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.4.5=py311ha034993_1
  - lz4-c=1.10.0=h2466b09_1
  - markupsafe=3.0.3=py311h3f79411_0
  - matplotlib=3.10.8=py311h1ea47a8_0
  - matplotlib-base=3.10.8=py311h1675fdf_0
  - mkl=2025.3.0=hac47afa_455
  - msgpack-python=1.1.2=py311h3fd045d_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - narwhals=2.16.0=pyhcf101f3_0
  - numba=0.63.1=py311h34437f8_0
  - numpy=2.3.5=py311h80b3fa1_1
  - openjpeg=2.5.4=h24db6dd_0
  - openssl=3.6.1=hf411b9b_1
  - orc=2.2.2=hbd3206f_0
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.0=py311h0610301_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.47=hd2b5f0e_0
  - pillow=12.1.0=py311h17b8079_0
  - pip=26.0.1=pyh8b19718_0
  - pixman=0.46.4=h5112557_1
  - pluggy=1.6.0=pyhf9edf01_1
  - psutil=7.2.2=py311hf893f09_0
  - pthread-stubs=0.4=h0e40799_1002
  - pyarrow=23.0.0=py311h1ea47a8_0
  - pyarrow-core=23.0.0=py311h819ed09_0_cuda
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - pyside6=6.10.2=py311hf70c7b4_0
  - pysocks=1.7.1=pyh09c184e_7
  - pytest=9.0.2=pyhcf101f3_0
  - python=3.11.14=h0159041_3_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pyyaml=6.0.3=py311h3f79411_1
  - qhull=2020.2=hc790b64_5
  - qt6-main=6.10.2=h68b6638_4
  - re2=2025.11.05=ha104f34_0
  - scipy=1.17.0=py311h9c22a71_1
  - setuptools=80.10.2=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - tbb=2022.3.0=h3155e25_2
  - tblib=3.2.2=pyhcf101f3_0
  - tk=8.6.13=h6ed50ae_3
  - tomli=2.4.0=pyhcf101f3_0
  - toolz=1.1.0=pyhd8ed1ab_1
  - tornado=6.5.4=py311h3485c13_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - ucrt=10.0.26100.0=h57928b3_0
  - unicodedata2=17.0.0=py311h3485c13_1
  - urllib3=2.6.3=pyhd8ed1ab_0
  - vc=14.3=h41ae7f8_34
  - vc14_runtime=14.44.35208=h818238b_34
  - vcomp14=14.44.35208=h818238b_34
  - vs2015_runtime=14.44.35208=h38c0c73_34
  - wheel=0.46.3=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyh7428d3b_8
  - xorg-libxau=1.0.12=hba3369d_1
  - xorg-libxdmcp=1.1.5=hba3369d_1
  - xyzservices=2025.11.0=pyhd8ed1ab_0
  - yaml=0.2.5=h6a83c73_3
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhcf101f3_1
  - zlib-ng=2.3.3=h0261ad2_1
  - zstd=1.5.7=h534d264_6

prefix: "C:\\Users\\srisb\\.local\\share\\mamba\\envs\\nsc2026"
